# Generated by Django 5.2 on 2025-04-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
